version: "1.0"
info:
  model: int-scaffold
packages:
- name: Shshi1124Project
  gitServerName: shshi
  gitUrl: https://github.com/Shilpa-Shivaji-IBM
  gitUsername: Shilpa-Shivaji-IBM
  gitBranch: main
